// ── 设置分类（左侧导航，顺序即 settings_tab 索引） ──

pub const CATEGORY_KEYS: [&str; 8] = [
    "settings.cat.theme",
    "settings.cat.appearance",
    "settings.cat.language",
    "settings.cat.audio",
    "settings.cat.render",
    "settings.cat.editing",
    "settings.cat.shortcuts",
    "settings.cat.general",
];

/// 设置项注册表（供搜索）：各语言名称均可直接检索。
/// 中文额外支持拼音（由 `to_search_keys` 运行时折叠，无需手写转写）。
pub struct SettingItem {
    pub cat: usize,
    pub zh: &'static str,
    pub en: &'static str,
    pub ja: &'static str,
    pub ko: &'static str,
}

pub const SETTING_ITEMS: &[SettingItem] = &[
    SettingItem {
        cat: 0,
        zh: "主题预设",
        en: "Theme preset",
        ja: "テーマプリセット",
        ko: "테마 프리셋",
    },
    SettingItem {
        cat: 0,
        zh: "背景",
        en: "Background color",
        ja: "背景色",
        ko: "배경색",
    },
    SettingItem {
        cat: 0,
        zh: "主文字",
        en: "Text color",
        ja: "テキスト色",
        ko: "텍스트 색",
    },
    SettingItem {
        cat: 0,
        zh: "强调色",
        en: "Accent color",
        ja: "アクセント色",
        ko: "강조색",
    },
    SettingItem {
        cat: 1,
        zh: "界面缩放",
        en: "UI scale",
        ja: "UI スケール",
        ko: "UI 배율",
    },
    SettingItem {
        cat: 1,
        zh: "字体大小",
        en: "Font size",
        ja: "フォントサイズ",
        ko: "글꼴 크기",
    },
    SettingItem {
        cat: 2,
        zh: "语言",
        en: "Language",
        ja: "言語",
        ko: "언어",
    },
    SettingItem {
        cat: 3,
        zh: "输出设备",
        en: "Output device",
        ja: "出力デバイス",
        ko: "출력 장치",
    },
    SettingItem {
        cat: 3,
        zh: "MIDI 输入设备",
        en: "MIDI input device",
        ja: "MIDI入力デバイス",
        ko: "MIDI 입력 장치",
    },
    SettingItem {
        cat: 3,
        zh: "MIDI 直通",
        en: "MIDI thru",
        ja: "MIDIスルー",
        ko: "MIDI 스루",
    },
    SettingItem {
        cat: 3,
        zh: "采样率",
        en: "Sample rate",
        ja: "サンプルレート",
        ko: "샘플 레이트",
    },
    SettingItem {
        cat: 3,
        zh: "缓冲区大小",
        en: "Buffer size",
        ja: "バッファサイズ",
        ko: "버퍼 크기",
    },
    SettingItem {
        cat: 3,
        zh: "合成器层数",
        en: "Synth layers",
        ja: "シンセレイヤー",
        ko: "신스 레이어",
    },
    SettingItem {
        cat: 3,
        zh: "合成引擎",
        en: "Synth engine",
        ja: "シンセエンジン",
        ko: "신스 엔진",
    },
    SettingItem {
        cat: 4,
        zh: "滚动模式",
        en: "Scroll mode",
        ja: "スクロールモード",
        ko: "스크롤 모드",
    },
    SettingItem {
        cat: 4,
        zh: "自动化密度",
        en: "Automation density",
        ja: "オートメーション密度",
        ko: "자동화 밀도",
    },
    SettingItem {
        cat: 4,
        zh: "音符描边",
        en: "Note outline",
        ja: "ノート枠線",
        ko: "노트 외곽선",
    },
    SettingItem {
        cat: 4,
        zh: "最小边框宽度",
        en: "Min border width",
        ja: "最小枠線幅",
        ko: "최소 테두리 폭",
    },
    SettingItem {
        cat: 4,
        zh: "GPU 裁剪",
        en: "GPU culling",
        ja: "GPU カリング",
        ko: "GPU 컬링",
    },
    SettingItem {
        cat: 2,
        zh: "MIDI 导入编码",
        en: "MIDI import encoding",
        ja: "MIDI インポートエンコーディング",
        ko: "MIDI 가져오기 인코딩",
    },
    SettingItem {
        cat: 3,
        zh: "刷新设备列表",
        en: "Refresh devices",
        ja: "デバイス更新",
        ko: "장치 새로고침",
    },
    SettingItem {
        cat: 6,
        zh: "快捷键",
        en: "Shortcuts",
        ja: "ショートカット",
        ko: "단축키",
    },
    SettingItem {
        cat: 6,
        zh: "恢复默认快捷键",
        en: "Reset shortcuts",
        ja: "ショートカット初期化",
        ko: "단축키 초기화",
    },
    SettingItem {
        cat: 7,
        zh: "恢复出厂设置",
        en: "Factory reset",
        ja: "工場出荷時リセット",
        ko: "공장 초기화",
    },
    SettingItem {
        cat: 5,
        zh: "允许重叠音符",
        en: "Allow overlapping notes",
        ja: "重なりノートを許可",
        ko: "겹치는 노트 허용",
    },
    SettingItem {
        cat: 5,
        zh: "重叠时移动策略",
        en: "Overlap move behavior",
        ja: "重なり時の移動動作",
        ko: "겹칠 때 이동 동작",
    },
    SettingItem {
        cat: 5,
        zh: "快速删除音符方式",
        en: "Quick delete note",
        ja: "クイック削除",
        ko: "빠른 삭제",
    },
];
