[package]
name = "yinhe-clap"
version = "0.1.0"
edition = "2024"

[dependencies]
clack-host = "0.1"
clack-extensions = { version = "0.1", features = [
    "clack-host",
    "audio-ports",
    "note-ports",
    "gui",
    "log",
    "latency",
    "params",
    "state",
    "state-context",
    "thread-check",
] }
thiserror = { workspace = true }
tracing = { workspace = true }
