[package]
name = "yinhe-synth"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1"
wgpu = { workspace = true, features = ["wgsl"] }
bytemuck = { workspace = true }
pollster = { workspace = true }
xsynth-soundfonts = "0.4"
hound = "3.5"
yinhe-mixer = { path = "../yinhe-mixer" }

[dev-dependencies]
yinhe-midi = { path = "../yinhe-midi" }
tempfile = { workspace = true }
xsynth-core = "0.4"
biquad = "0.4"
